version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: nestapp/music:1.0.0
    build:
      context: .
      target: development
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    environment:
      DB_TYPE: ${PG_DB_TYPE}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    container_name: db-music
    image: postgres:12
    restart: unless-stopped
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
volumes:
  db-data:
  db-logs:

networks:
  user-defined:
    driver: bridge
    name: 'user-defined'
